### ISSUE TITLE
S3 Button labeling and lower icons

### ISSUE THREAD

**Issue by rgbetanco** [rgbetanco/SmartPlug#2]
S3 has two buttons, one for the start time and the other for the end time, if the time is 12:00 only one zero is displayed 12:0, two zeros need to be displayed.

Below those buttons there is an action section, that section please hide it for now, until we get a defined resolution from customer.

**Comment by chinyu** [comment]
Standardized timer time formatting (use Miscellaneous.getTime( hr, min ) )
